services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=ecommercedb'
      - 'POSTGRES_PASSWORD=banco321'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
